# Generated by Django 4.2.5 on 2023-10-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='user',
            name='email_id',
            field=models.CharField(default='pickleprat@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
