# Generated by Django 4.2.5 on 2023-10-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
    ]
