# Generated by Django 4.2.5 on 2023-10-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
