# Generated by Django 4.2.5 on 2023-10-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_order_ship_city_alter_order_ship_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Denormalized',
        ),
    ]
