# Generated by Django 4.2.5 on 2023-10-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_order_denormalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denormalized',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='b2b',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='courier_status',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='date',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='fulfilment',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='sales_channel',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='ship_city',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='ship_service_level',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='ship_state',
        ),
        migrations.RemoveField(
            model_name='denormalized',
            name='status',
        ),
        migrations.AddField(
            model_name='denormalized',
            name='CourierStatus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='SalesChannel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='shipcity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='shipservicelevel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='shipstate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='denormalized',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='denormalized',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='denormalized',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='denormalized',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='B2B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='Date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='Fulfilment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='Qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='denormalized',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
