# Generated by Django 4.2.5 on 2023-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_denormalized_amount_remove_denormalized_b2b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denormalized',
            name='Date',
            field=models.DateField(),
        ),
    ]
