# Generated by Django 4.2.5 on 2023-10-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_denormalized_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denormalized',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='denormalized',
            old_name='B2B',
            new_name='b2b',
        ),
        migrations.RenameField(
            model_name='denormalized',
            old_name='CourierStatus',
            new_name='courierStatus',
        ),
        migrations.RenameField(
            model_name='denormalized',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='denormalized',
            old_name='Fulfilment',
            new_name='fulfilment',
        ),
        migrations.RenameField(
            model_name='denormalized',
            old_name='Qty',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='denormalized',
            old_name='SalesChannel',
            new_name='salesChannel',
        ),
        migrations.RenameField(
            model_name='denormalized',
            old_name='Status',
            new_name='status',
        ),
    ]
