# Generated by Django 4.2.5 on 2023-10-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_amount_denormalized_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denormalized',
            old_name='courierStatus',
            new_name='courierstatus',
        ),
        migrations.RenameField(
            model_name='denormalized',
            old_name='salesChannel',
            new_name='saleschannel',
        ),
    ]
