# Generated by Django 4.2.5 on 2023-10-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('stock', models.DecimalField(decimal_places=1, max_digits=10)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.style')),
            ],
        ),
    ]
