# Generated by Django 4.2.5 on 2023-10-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_asin_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='style',
            name='style_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
