# Generated by Django 4.2.5 on 2023-10-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_style_category_alter_style_style_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.BigIntegerField(verbose_name='zip code')),
                ('city_name', models.CharField(max_length=100, verbose_name='city name')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
            ],
        ),
    ]
