# Generated by Django 4.2.5 on 2023-10-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='zip code'),
        ),
    ]
