# Generated by Django 4.2.5 on 2023-10-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_city_id_alter_city_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('fulfilment', models.CharField(max_length=100)),
                ('saleschannel', models.CharField(max_length=100)),
                ('shipservicelevel', models.CharField(max_length=100)),
                ('courierstatus', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b2b', models.BooleanField()),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city')),
            ],
        ),
    ]
